
name: pre-commit

on:
  pull_request:
    branches:
      - "18.0*"
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: '.pre-commit-config.yaml'
      - name: Get python version
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure --color=always
        env:
          # Consider valid a PR that changes README fragments but doesn't
          # change the README.rst file itself. It's not really a problem
          # because the bot will update it anyway after merge. This way, we
          # lower the barrier for functional contributors that want to fix the
          # readme fragments, while still letting developers get README
          # auto-generated (which also helps functionals when using runboat).
          # DOCS https://pre-commit.com/#temporarily-disabling-hooks
          SKIP: oca-gen-addon-readme
      - name: Check that all files generated by pre-commit are in git
        run: |
          newfiles="$(git ls-files --others --exclude-from=.gitignore)"
          if [ "$newfiles" != "" ] ; then
              echo "Please check-in the following files:"
              echo "$newfiles"
              exit 1
          fi
      - name: Check that vendored libs have declared their origin and match
        shell: python
        run: |
          import subprocess
          import hashlib
          from pathlib import Path
          from logging import getLogger

          _logger = getLogger("check-vendor-libs")


          def main(checklist, warn_mode=False):
              warn_mode = False

              for to_check in checklist:
                  for path in Path(".").glob(to_check):
                      check_entries(path)


          def check_entries(path: Path):
              """
              find pairs of $file, .$file.vendor-origin and run the checker on them
              error for all files without vendor origin or vendor origins without file
              """
              result = True
              entries = {}

              for entry in path.iterdir():
                  if entry.name.startswith(".") and entry.suffix == ".vendor-origin":
                      if entry in entries:
                          entries[entry] = entries.pop(entry)
                      else:
                          entries[entry] = NotFound()
                  else:
                      origin = path / (f".{entry.name}.vendor-origin")
                      if origin in entries:
                          del entries[origin]
                          entries[origin] = entry
                      else:
                          entries[NotFound(origin)] = entry

              for origin, vendorfile in entries.items():
                  if isinstance(origin, NotFound):
                      if vendorfile.is_dir():
                          result &= check_entries(vendorfile)
                      else:
                          result = False
                          _logger.error(f"{vendorfile} has not declared origin")
                  elif isinstance(vendorfile, NotFound):
                      result = False
                      _logger.error(f"{origin} doesnt refer to anything")
                  else:
                      origin_lines = list(
                          filter(
                              lambda x: not x.startswith("#"),
                              map(str.strip, origin.read_text().splitlines()),
                          )
                      )
                      if len(origin_lines) != 1 or " " not in origin_lines[0]:
                          _logger.error(f"{origin} is malformed")
                          return False

                      git_url, revision = origin_lines[0].split(" ", 1)
                      subdir = None
                      if " " in revision:
                          revision, subdir = revision.split(" ", 1)
                      result &= compare(vendorfile, git_url, revision, subdir)

              return result


          def compare(vendorfile: Path, git_url: str, revision: str, subdir: str | None):
              """
              clone from origin and compare vendorfile with version in origin
              error if file is not found or doesn't match
              """
              git_dir = (
                  Path.home()
                  / ".cache"
                  / "check-vendor-libs"
                  / hashlib.sha256(f"{git_url}@{revision}".encode("utf8")).hexdigest()
              )

              def git(*args):
                  return subprocess.run(("git", "-C", git_dir) + args, capture_output=True)

              if not git_dir.exists():
                  git_dir.mkdir(parents=True, exist_ok=True)
                  git("init")
                  git("remote", "add", "origin", git_url)
                  git("fetch", "origin", revision)
                  git("checkout", "FETCH_HEAD")

              git_file = git_dir / Path(subdir) / vendorfile.name

              if not git_file.exists():
                  _logger.error(f"{vendorfile} does not exist in origin {git_url}@{revision}")
                  return False

              with (
                  vendorfile.open("rb") as vendorfile_handle,
                  git_file.open("rb") as git_file_handle,
              ):
                  vendorfile_digest = hashlib.file_digest(vendorfile_handle, "sha256").digest()
                  git_file_digest = hashlib.file_digest(git_file_handle, "sha256").digest()
                  if vendorfile_digest != git_file_digest:
                      _logger.error(f"{vendorfile} differs from version in {git_url}@{revision}")
                      subprocess.run(["diff", vendorfile, git_file])
                      return False

              return True


          class NotFound(Path):
              pass


          def git(*args):
              return subprocess.run(["git"] + args)


          main(["*/static/lib"])
